### ISSUE TITLE
Request for version patches reflecting updates on the master branch

### ISSUE THREAD

**Issue by leolux** [vert-x3/vertx-bus-bower#2]
The current bower version is "3.0.0" and waiting for the release of "3.1.0" slows down my development process because other components make use of this bower component. 

Generally spoken: Who wants to develop with code which is 4 weeks old?

I whish that this bower component gets patched for every change of the master file https://github.com/vert-x3/vertx-web/blob/master/src/client/vertxbus.js.

This could be done by adding a path-version in the following way during the ongoing version "3.1.0-SNAPHOT":
"3.1.0-SNAPHOT.1","3.1.0-SNAPHOT.2","3.1.0-SNAPHOT.3", etc.

http://semver.org/

**Comment by cescoffier** [comment]
Hi,

We don't make publicly available development version, because they need to be double-checked before. So, Bower is going to be updated when vert.x 3.1 will be release. The good news is that it should happen shortly. 

If you need this file, either take it from the vertx-web repository (at your own risk, as it's a development version) and install it on your own Bower registry. (http://toranbillups.com/blog/archive/2013/08/04/How-to-host-a-private-bower-registry/).
